Repository mabenal/library-management-system, pull requests merged in 2025-01, with the labels that each got.

#12 books modal creation
  client/generate.constants.js
  client/override.js
  client/package.json
  client/src/app/app.component.html
  client/src/app/app.component.ts
  client/src/app/app.module.ts
  client/src/constants/constants.ts
  client/src/constants/index.ts
  client/src/resources/Resources.resx
  client/src/shared-components/book-details-modal/book-details-modal.component.html
  client/src/shared-components/book-details-modal/book-details-modal.component.less
  client/src/shared-components/book-details-modal/book-details-modal.component.spec.ts
  client/src/shared-components/book-details-modal/book-details-modal.component.ts
  client/src/styles.less
Labels: bug, Feature

#13 Feature/client controllers crud operations/sm 0.0.1
  client/package-lock.json
  server/lms-server/lms-server/Controllers/ClientController.cs
  server/lms-server/lms-server/Data/LmsDbContext.cs
  server/lms-server/lms-server/Mappings/AutoMapperProfiles.cs
  server/lms-server/lms-server/Migrations/20250114135502_Migration-For-Database.Designer.cs
  server/lms-server/lms-server/Migrations/20250114135502_Migration-For-Database.cs
  server/lms-server/lms-server/Migrations/LmsDbContextModelSnapshot.cs
  server/lms-server/lms-server/Program.cs
  server/lms-server/lms-server/Repository/IBooksRepository.cs
  server/lms-server/lms-server/Repository/IClientRepository.cs
  server/lms-server/lms-server/Repository/SQLBooksRepository.cs
  server/lms-server/lms-server/Repository/SQLClientRepository.cs
  server/lms-server/lms.Abstractions/Models/DTO/ClientDto.cs
Labels: Feature

#25 Feature/added book request history end points/sm 0.0.1
  server/lms-server/lms-server/Migrations/20250121200835_Initial Migration.Designer.cs
  server/lms-server/lms-server/Migrations/20250121200835_Initial Migration.cs
  server/lms-server/lms-server/Migrations/LmsDbContextModelSnapshot.cs
  server/lms-server/lms-server/appsettings.json
  server/lms-server/lms.Abstractions/Data/LmsDbContext.cs
  server/lms-server/lms.Abstractions/Interfaces/IBookRequestRepository.cs
  server/lms-server/lms.Abstractions/Mappings/AutoMapperProfiles.cs
  server/lms-server/lms.Abstractions/Models/BookRequest.cs
  server/lms-server/lms.Abstractions/Models/DTO/BookRequestDto.cs
  server/lms-server/lms.Peer/Controllers/BookRequestController.cs
  server/lms-server/lms.Services/Repository/SQLBookRequestRepository.cs
  server/lms-server/lms.Services/Repository/SQLBooksRepository.cs
  server/lms-server/lms.Services/ServiceExecutionCollection.cs
Labels: Feature

#40 Enhancment/book request validation/sm 0.0.2
  server/lms-server/lms.Abstractions/Exceptions/GoblalException.cs
  server/lms-server/lms.Abstractions/Interfaces/IBookRequestRepository.cs
  server/lms-server/lms.Abstractions/Models/BookRequest.cs
  server/lms-server/lms.Abstractions/Models/DTO/BookRequestDto.cs
  server/lms-server/lms.Peer/Controllers/BookRequestController.cs
  server/lms-server/lms.Peer/Controllers/BooksController.cs
  server/lms-server/lms.Services/Repository/SQLBookRequestRepository.cs
  server/lms-server/lms.Services/Repository/SQLBooksRepository.cs
Labels: enhancement, Feature

#48 Added state design pattern
  server/lms-server/lms-server/Migrations/20250131084941_book.Designer.cs
  server/lms-server/lms-server/Migrations/20250131084941_book.cs
  server/lms-server/lms-server/Migrations/LmsDbContextModelSnapshot.cs
  server/lms-server/lms-server/Program.cs
  server/lms-server/lms.Abstractions/ConfigurationManager.cs
  server/lms-server/lms.Abstractions/Exceptions/GoblalException.cs
  server/lms-server/lms.Abstractions/Interfaces/IBookRequestRepository.cs
  server/lms-server/lms.Abstractions/Interfaces/IBookRequestState.cs
  server/lms-server/lms.Abstractions/Interfaces/IClientRepository.cs
  server/lms-server/lms.Abstractions/Models/ApplicationUser.cs
  server/lms-server/lms.Abstractions/Models/Book.cs
  server/lms-server/lms.Abstractions/Models/BookRequest.cs
  server/lms-server/lms.Abstractions/Models/Client.cs
  server/lms-server/lms.Abstractions/Models/DTO/BookDto.cs
  server/lms-server/lms.Abstractions/Models/DTO/BookRequestDto.cs
  server/lms-server/lms.Abstractions/Models/DTO/ClientDto.cs
  server/lms-server/lms.Abstractions/Models/DTO/LoginDto.cs
  server/lms-server/lms.Abstractions/Models/DTO/RegisterDto.cs
  server/lms-server/lms.Abstractions/Models/States/ApprovedState.cs
  server/lms-server/lms.Abstractions/Models/States/CancelledState.cs
  server/lms-server/lms.Abstractions/Models/States/OverdueState.cs
  server/lms-server/lms.Abstractions/Models/States/PendingState.cs
  server/lms-server/lms.Abstractions/Models/States/ReturnedState.cs
  server/lms-server/lms.Peer/Controllers/AccountController.cs
  server/lms-server/lms.Peer/Controllers/BookRequestController.cs
  server/lms-server/lms.Peer/Controllers/BooksController.cs
  server/lms-server/lms.Peer/Controllers/ClientController.cs
  server/lms-server/lms.Services/Repository/SQLBookRequestRepository.cs
  server/lms-server/lms.Services/Repository/SQLBooksRepository.cs
  server/lms-server/lms.Services/Repository/SQLClientRepository.cs
  server/lms-server/lms.Services/Repository/TokenRepository.cs
  server/lms-server/lms.Services/ServiceExecutionCollection.cs
Labels: enhancement
